apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend-application-deployment
  labels: frontend-application-deployment
spec: 
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      name: frontend
      labels:
        app:frontend
    spec:
      containers:
      - name: frontend-container
        image: kimutaikk/client_image_yolo:v1.0.3
        imagePullPolicy: "Always"

        ports: 
        - containerPort: 3000
