apiVersion: apps /v1 
kind: Deployment
metadata:
  name: frontend application deployment
spec: 
  selector:
    matchLabels:
      app: nodejs
  replicas:2
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: frontend_container
        image: kimutaikk/client_image_yolo:v1.0.1
        ports: 
        - containerPort: 3001
