apiVersion: v1
kind: Service
metadata:
  name: frontend-application-service
  # labels:
  #   app: frontend-application-service
spec:
  type: LoadBalancer
  selector: 
    app: frontend
  ports:

  - protocol: TCP
    port: 3000
    targetPort: 3000
