apiVersion: v1
kind: Service
metadata:
  name: frontend-application-service
spec:
  type: LoadBalancer
  selector: 
    app: backend-application-service
    tier: frontend
  ports:

  - name: http 
    port: 80
    targetPort: 3000
