apiVersion: apps /v1 
kind: Deployment
metadata:
  name: frontend-application-deployment
  # labels: frontend_app
spec: 
  selector:
    matchLabels:
      app: frontend-application-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-application-deployment
    spec:
      containers:
      - name: frontend_container
        image: kimutaikk/client_image_yolo:v1.0.1
        ports: 
        - containerPort: 3001
