apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend-application-deployment
  # labels: frontend_app
spec: 
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: kimutaikk/client_image_yolo:v1.0.2
        imagePullPolicy: "Always"

        ports: 
        - containerPort: 3000
