version: "3.8"

services:



  mongo:
    image: mongo:latest
    container_name: 'kevins-mongodb-container'
    restart: always
    
    ports:
      - "27017:27017"

    
    volumes:
      # volume where db data is stored for perstitence
      - my_yolo_vol:/data/db 

    networks:
      - yolo_network


  backend:
    image: kimutaikk/backend_image_yolo:v1.0.2
    depends_on:
      - mongo
    # build: ./backend
    restart: always
    env_file: ./.env
    ports:
      - 5000:5000
   
    networks:
      - yolo_network
   


  client:
    image: kimutaikk/client_image_yolo:v1.0.0
     
    # build: ./client
    ports: 
      - 3000:3000
    # stdin_open: true
    # tty: true 
    depends_on:
      - backend
   
volumes:
  my_yolo_vol: {}


networks:
  yolo_network:
      driver: bridge


