version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - yolo_vol:/data/db
    networks:
      - yolo_network

    
  mongo-express:
    image: mongo-express
    restart: unless-stopped

    ports:
      - 8081:8081

    environment:
      
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_URL=mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo:27017/?authSource=admin
    links:
      - mongo
    
  backend:
    depends_on:
      - mongodb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
    stdin_open: true
    tty: true

  client:
    build: ./client
    ports: 
      - 3000:3000
    stdin_open: true
    tty: true 
    depends_on:
      - backend
    volumes:
      - yolo_vol:/data/db
volumes:
  yolo_vol:
      driver: local  

networks:
  mongo_network:
    external:true


