---


  #install packages for all hosts 
- name: Install Packages  
  become: yes
  hosts:  all


  tasks:
      # Install aptitude package manager for Debian-based systems
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    # Install packages essential for running a developer environment 
    # on a Debian-based system.
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - nodejs
          - npm 
        state: latest
        update_cache: true

    # Sets key used to verify your install packages are from an authorized source.
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # Sets repository containing packages needed to install
    # and run Docker on a Debian-based system.
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    # Installs Docker community edition
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    # Installs Docker Module for Python.
    # Allows you to manage Docker containers from within Ansible playbooks.
    - name: Install Docker Module for Python
      pip:
        name: docker




   #Play Run the Mongo DB Server

- name: Install and configure MongoDB
  hosts: mongo
  become: true
  # vars:
  #   mongo_version: "4.4"
  #   mongo_admin_user: admin
  #   mongo_admin_password: mypassword
  #   mongo_auth_db: admin
  tasks:
    # - name: Import MongoDB public GPG Key
    #   apt_key:
    #     url: https://www.mongodb.org/static/pgp/server-4.4.asc
    #     state: present

    # - name: Add MongoDB repository
    #   apt_repository:
    #     repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse
    #     state: present

    # - name: Install MongoDB
    #   apt:
    #     name: mongodb-org
    #     state: present

    # - name: Start MongoDB service
    #   systemd:
    #     name: mongod
    #     enabled: yes
    #     state: started

    - name: pull mongo latest container
       
      docker_image:
        name: mongo:latest
        source: pull

    - name: Run the mongo container
      
      docker_container: 
        image: mongo:latest
        name: kevins-mongodb-container
        state: started
        ports: 27017:27017

    - name: Specify the network 
      docker_network:
        name: yolo_network
        connected: 
          - kevins-mongodb-container


   
    - name: Specify the volume
      docker_volume:
        name: my_yolo_vol:data/db

  #Play 1 - Backend server related tasks
- name: Play Backend - Install required dependencies , pull image and start contianer
  become: yes
  hosts: backend





 
  tasks:
    - name: Pull backend image
       
      docker_image:
        name: kimutaikk/backend_image_yolo:v1.0.3
        source: pull

    - name: Run the  backend container using the backend image from docker hub 
      
      docker_container: 
        image: kimutaikk/backend_image_yolo:v1.0.3
        name: backend_container
        state: started
        ports: 2222:5001
      
    - name: Specify the volume
      docker_volume:
        name: my_yolo_vol:data/db
    
    - name: Specify the network 
      docker_network:
        name: yolo_network
        connected: 
          - backend_container







  

  #Play 2 - Client server related tasks
- name: Play Client - Install required dependencies , pull image and start contianer
  become: yes
  hosts: frontend



  tasks:
    
        
    - name: Pull client image
      
      docker_image:
        name: kimutaikk/client_image_yolo:v1.0.1
        source: pull

    - name: Run the  client container using the client image from docker hub 
      
      docker_container: 
        image: kimutaikk/client_image_yolo:v1.0.1
        name: client_container
        state: started
        ports: 2200:3001
      
    - name: Specify the network 
      docker_network:
        name: yolo_network
        connected: 
          - client_container



 
   
    
        