apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  password: WDhEeEs5ZDR4OGkyS3RPeA==
---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: backend-application-deployment
  # labels: backend
spec: 
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: backend-container
        image: kimutaikk/backend_image_yolo:v1.2.8
        imagePullPolicy: "Always"
        ports: 
        - containerPort: 5000
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
