apiVersion: v1
kind: Service
metadata:
  name: backend-application-service
  # labels:
  #   app: backend-application-service
spec:
  type: LoadBalancer
  selector: 
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
