apiVersion: apps/v1 
kind: Deployment
metadata:
  name: backend-application-deployment
  # labels: frontend_app
spec: 
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: backend-container
        image: kimutaikk/backend_image_yolo:v1.2.0
        imagePullPolicy: "Always"
        ports: 
        - containerPort: 5000
        # env:
        # - name: CONN_STR
        #   value: ""
